### ISSUE TITLE
Plugin crash when using NopSCADlib

### ISSUE THREAD

**Issue by gooostaw** [Leathong/openscad-support-vscode#15]
Hi.  When I use NopSCADlib the whole plugin crashes. Just this simple code and hover over the "extrusion" is enough:
```
include <NopSCADlib/core.scad>
include <NopSCADlib/vitamins/extrusions.scad>

extrusion(E2020, 20);
```
OpenSCAD-LSP output:
```
[server] start with socket
[client] Connecting to openscad on port 3245
[server] start sucess

[server] search paths:
[server] file:///home/gooostaw/.local/share/OpenSCAD/libraries/
[server] file:///usr/share/openscad/libraries/

thread 'main' panicked at 'already borrowed: BorrowMutError', src/server/code_helper.rs:145:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 3:07:12 AM] Connection to server got closed. Server will restart.
[client] Connecting to openscad on port 3245
[Error - 3:07:12 AM] Client OpenSCAD Language Server: connection to server is erroring. Shutting down server.
[Error - 3:07:12 AM] Client OpenSCAD Language Server: connection to server is erroring. Shutting down server.
[Error - 3:07:12 AM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at LanguageClient.shutdown (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:897:19)
	at LanguageClient.stop (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:868:21)
	at LanguageClient.stop (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/node/main.js:150:22)
	at LanguageClient.handleConnectionError (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:1104:18)
	at errorHandler (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:1047:18)
	at /home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:1417:36
	at CallbackList.invoke (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at writeErrorHandler (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/connection.js:299:22)
	at CallbackList.invoke (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageWriter.fireError (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:36:27)
	at Socket.<anonymous> (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:73:47)
	at Socket.emit (node:events:525:35)
	at Socket.emit (node:domain:489:12)
	at emitErrorNT (node:internal/streams/destroy:157:8)
	at emitErrorCloseNT (node:internal/streams/destroy:122:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[Error - 3:07:12 AM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at LanguageClient.shutdown (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:897:19)
	at LanguageClient.stop (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:868:21)
	at LanguageClient.stop (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/node/main.js:150:22)
	at LanguageClient.handleConnectionError (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:1104:18)
	at errorHandler (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:1047:18)
	at /home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:1417:36
	at CallbackList.invoke (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at readErrorHandler (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/connection.js:296:22)
	at CallbackList.invoke (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageReader.fireError (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/messageReader.js:34:27)
	at Socket.<anonymous> (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/messageReader.js:123:47)
	at Socket.emit (node:events:525:35)
	at Socket.emit (node:domain:489:12)
	at emitErrorNT (node:internal/streams/destroy:157:8)
	at emitErrorCloseNT (node:internal/streams/destroy:122:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[Info  - 3:07:12 AM] Connection to server got closed. Server will restart.
[client] Connecting to openscad on port 3245
[Error - 3:07:12 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 3:07:12 AM] OpenSCAD Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 3:07:12 AM] Client OpenSCAD Language Server: connection to server is erroring. Shutting down server.
[Error - 3:07:12 AM] Client OpenSCAD Language Server: connection to server is erroring. Shutting down server.
[Error - 3:07:12 AM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
	at LanguageClient.shutdown (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:897:19)
	at LanguageClient.stop (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:868:21)
	at LanguageClient.stop (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/node/main.js:150:22)
	at LanguageClient.handleConnectionError (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:1104:18)
	at errorHandler (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:1047:18)
	at /home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:1417:36
	at CallbackList.invoke (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at writeErrorHandler (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/connection.js:299:22)
	at CallbackList.invoke (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageWriter.fireError (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:36:27)
	at Socket.<anonymous> (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:73:47)
	at Socket.emit (node:events:525:35)
	at Socket.emit (node:domain:489:12)
	at emitErrorNT (node:internal/streams/destroy:157:8)
	at emitErrorCloseNT (node:internal/streams/destroy:122:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[Error - 3:07:12 AM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
	at LanguageClient.shutdown (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:897:19)
	at LanguageClient.stop (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:868:21)
	at LanguageClient.stop (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/node/main.js:150:22)
	at LanguageClient.handleConnectionError (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:1104:18)
	at errorHandler (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:1047:18)
	at /home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:1417:36
	at CallbackList.invoke (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at readErrorHandler (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/connection.js:296:22)
	at CallbackList.invoke (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageReader.fireError (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/messageReader.js:34:27)
	at Socket.<anonymous> (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/messageReader.js:123:47)
	at Socket.emit (node:events:525:35)
	at Socket.emit (node:domain:489:12)
	at emitErrorNT (node:internal/streams/destroy:157:8)
	at emitErrorCloseNT (node:internal/streams/destroy:122:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[Info  - 3:07:12 AM] Connection to server got closed. Server will restart.
[client] Connecting to openscad on port 3245
[Error - 3:07:12 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 3:07:12 AM] OpenSCAD Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 3:07:12 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 3:07:12 AM] Client OpenSCAD Language Server: connection to server is erroring. Shutting down server.
[Error - 3:07:12 AM] Client OpenSCAD Language Server: connection to server is erroring. Shutting down server.
[Error - 3:07:12 AM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
	at LanguageClient.shutdown (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:897:19)
	at LanguageClient.stop (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:868:21)
	at LanguageClient.stop (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/node/main.js:150:22)
	at LanguageClient.handleConnectionError (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:1104:18)
	at errorHandler (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:1047:18)
	at /home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:1417:36
	at CallbackList.invoke (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at writeErrorHandler (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/connection.js:299:22)
	at CallbackList.invoke (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageWriter.fireError (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:36:27)
	at Socket.<anonymous> (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:73:47)
	at Socket.emit (node:events:525:35)
	at Socket.emit (node:domain:489:12)
	at emitErrorNT (node:internal/streams/destroy:157:8)
	at emitErrorCloseNT (node:internal/streams/destroy:122:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[Error - 3:07:12 AM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
	at LanguageClient.shutdown (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:897:19)
	at LanguageClient.stop (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:868:21)
	at LanguageClient.stop (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/node/main.js:150:22)
	at LanguageClient.handleConnectionError (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:1104:18)
	at errorHandler (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:1047:18)
	at /home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:1417:36
	at CallbackList.invoke (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at readErrorHandler (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/connection.js:296:22)
	at CallbackList.invoke (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageReader.fireError (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/messageReader.js:34:27)
	at Socket.<anonymous> (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/messageReader.js:123:47)
	at Socket.emit (node:events:525:35)
	at Socket.emit (node:domain:489:12)
	at emitErrorNT (node:internal/streams/destroy:157:8)
	at emitErrorCloseNT (node:internal/streams/destroy:122:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[Info  - 3:07:12 AM] Connection to server got closed. Server will restart.
[client] Connecting to openscad on port 3245
[Error - 3:07:12 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 3:07:12 AM] OpenSCAD Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 3:07:12 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 3:07:12 AM] Client OpenSCAD Language Server: connection to server is erroring. Shutting down server.
[Error - 3:07:12 AM] Client OpenSCAD Language Server: connection to server is erroring. Shutting down server.
[Error - 3:07:12 AM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
	at LanguageClient.shutdown (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:897:19)
	at LanguageClient.stop (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:868:21)
	at LanguageClient.stop (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/node/main.js:150:22)
	at LanguageClient.handleConnectionError (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:1104:18)
	at errorHandler (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:1047:18)
	at /home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:1417:36
	at CallbackList.invoke (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at writeErrorHandler (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/connection.js:299:22)
	at CallbackList.invoke (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageWriter.fireError (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:36:27)
	at Socket.<anonymous> (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:73:47)
	at Socket.emit (node:events:525:35)
	at Socket.emit (node:domain:489:12)
	at emitErrorNT (node:internal/streams/destroy:157:8)
	at emitErrorCloseNT (node:internal/streams/destroy:122:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[Error - 3:07:12 AM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
	at LanguageClient.shutdown (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:897:19)
	at LanguageClient.stop (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:868:21)
	at LanguageClient.stop (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/node/main.js:150:22)
	at LanguageClient.handleConnectionError (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:1104:18)
	at errorHandler (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:1047:18)
	at /home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-languageclient/lib/common/client.js:1417:36
	at CallbackList.invoke (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at readErrorHandler (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/connection.js:296:22)
	at CallbackList.invoke (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageReader.fireError (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/messageReader.js:34:27)
	at Socket.<anonymous> (/home/gooostaw/.vscode/extensions/leathong.openscad-language-support-1.2.4/node_modules/vscode-jsonrpc/lib/common/messageReader.js:123:47)
	at Socket.emit (node:events:525:35)
	at Socket.emit (node:domain:489:12)
	at emitErrorNT (node:internal/streams/destroy:157:8)
	at emitErrorCloseNT (node:internal/streams/destroy:122:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[Error - 3:07:12 AM] The OpenSCAD Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 3:07:12 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 3:07:12 AM] OpenSCAD Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 3:07:12 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 

```

**Comment by Leathong** [comment]
Thanks for feedback, but I am really busy with my work recently, it will be fixed later.

**Comment by Leathong** [comment]
There was a circular including between screw.scad and nut.scad, it looks weird.

**Comment by Leathong** [comment]
update to 1.2.5
